
export const SAVE_SESSION: string = 'SAVE_SESSION';

export const GAME: any = {

    START: 'START_GAME',
    END: 'END_GAME',
    RESTART: 'RESTART_GAME',

    SNAKE_MOVE_TOP: 'SNAKE_MOVE_TOP',
    SNAKE_MOVE_LEFT: 'SNAKE_MOVE_LEFT',
    SNAKE_MOVE_BOTTOM: 'SNAKE_MOVE_BOTTOM',
    SNAKE_MOVE_RIGHT: 'SNAKE_MOVE_RIGHT',

    SNAKE_EAT: 'SNAKE_EAT',

};

export default {
    SAVE_SESSION,
};